### ISSUE TITLE
Agent does not progress without powershell

### ISSUE THREAD

**Issue by s-monzon** [Ylianst/MeshAgent#102]
I parsed the agent code trying to evade Powershell, but I can't.
Is there a way to get this function with CMD?

generally to create firewall rules we use:

netsh advfirewall firewall add rule name = test dir = in action = allow protocol = localport =

Thank you

**Comment by krayon007** [comment]
So originally I was using that too, but found that MSFT has deprecated that usage, so on some versions of windows that does not work, which is why it tries to use powershell, falling back to netsh. The easiest workaround for you, is to modify win-firewall.js. Scroll to the bottom of the file, to where the module.exports are defined inside an if block:
`if (netsecurityExists())`
comment out the entire section where this evaluates to true, leaving only the netsh version. This will force the agent to use netsh to manipulate the firewall...  However, I should tell you, that the agent uses powershell for a number of other things, so if your platform/configuration doesn't allow powershell, a lot of other features could function incorrectly.

**Comment by s-monzon** [comment]
Perfect, I modify and inform how the result is

Thanks

**Comment by krayon007** [comment]
I forgot to mention. After you modify win-firewall.js, you need to make sure that modified file is included in the same folder as the binary. Otherwise the agent will load the original version.

**Comment by s-monzon** [comment]
The advice was carried out, the powershell barrier was overcome, the other functions were checked and everything works perfectly.
After placing the win-firewall.js file on the server, we also had to place the same file next to the agent's installer, to complete the installation.

Thanks for everything

**Comment by s-monzon** [comment]
the powershel problem, it was concluded everything works perfectly
