### ISSUE TITLE
 The provider does not trust the root certificate

### ISSUE THREAD

**Issue by skrdanl** [Ylianst/MeshAgent#116]
![Capture](https://user-images.githubusercontent.com/95742062/145989698-2e6ed47e-ab3a-4345-8f25-6860cefbbe40.PNG)

**Comment by Ylianst** [comment]
This is normal. The MeshAgent.exe is signed with a self-signed root certificate. If you have a code signing certificate, you are welcome to sign the executable yourself, it is in the "node_modules/agents/MeshService-signed.exe" and "node_modules/agents/MeshService64-signed.exe".

I don't sign the agent using a real code signing certificate since the agent can be used to do bad things and I have gotten my code signing certificate revoked in the past. Hope that helps.
