### ISSUE TITLE
How to activate console.info1() - messages?

### ISSUE THREAD

**Issue by wdlut** [Ylianst/MeshAgent#140]
I can see the console.log()/.warn()/.error() messages on the console, but not the console.info1/2 messages.
How could I activate them?

**Comment by krayon007** [comment]
to active those levels, execute the command, substituting n with an integer between 0 and 5
`console.setInfoLevel(n);`

After executing the above command, the console.info commands will redirect to console.log if the info level is less than or equal to what was specified in setInfoLevel. Otherwise, it will no-op. The default is 0.

**Comment by si458** [comment]
just tagging onto this for my notes:
you run `eval "console.setInfoLevel(n)"` from within the console tab,
and you must also have run the agent at the command line with `meshagent.exe run`
