### ISSUE TITLE
meshagent.db not being removed on -fullinstall

### ISSUE THREAD

**Issue by kpetrow** [Ylianst/MeshAgent#240]
I have machines move from site to site and need to have installers that change the group and the meshagent.tag file. A new installer is used to overwrite the previous one the meshagent.db file is left and stores/caches the previous meshagent.tag file.  I also notice that the files are still there when i manually uninstall. This causes the new installed mesh agent to load the meshagent.db file and not create a new one

**Comment by kpetrow** [comment]
windows. work around is to stop service delete meshAgent.db and restart service.  Seems to work

**Comment by si458** [comment]
thats weird because again its suppose to STOP the service first before it removes everything.
so if its removing the exe but not the db then it must be somethig else cuzing this bug

can you share logs you get from when you run the fulluninstall from the command line?
`C:\Program Files\MeshAgent\MeshAgent\meshagent.exe -fulluninstall` ?

**Comment by kpetrow** [comment]
This issue is only occurring when it runs as a service. If i stop the service and run through the UI it works properly and connects to correct group with the correct mesh agent tag.

install script used

```
START /WAIT "" "%~dp0meshAgent.exe" -fullinstall
echo randomTag > "C:\Program Files\Mesh Agent\meshagent.tag
echo agentName=randomTag >> "C:\Program Files\Mesh Agent\meshagent.msh"
net stop "Mesh Agent" && net start "Mesh Agent"
```

restarting the service does not work. It is also connecting to the wrong group

**Comment by si458** [comment]
You are using the wrong command...
I edited ur title because I through u had misspelt the command 
`-fullinstall` is used to install the agent, and even if an agent exists it won't touch the .db file! Only remove the exes and msh file
You have to uninstall with `-fulluninstall` then download ur exe and use `-fullinstall`

**Comment by kpetrow** [comment]
after uninstall
![image](https://github.com/Ylianst/MeshAgent/assets/18248938/be0e6b6b-df27-43be-8d79-9d81637482e3)

**Comment by si458** [comment]
> after uninstall ![image](https://private-user-images.githubusercontent.com/18248938/327565970-be0e6b6b-df27-43be-8d79-9d81637482e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2Nzg5OTksIm5iZiI6MTcxNDY3ODY5OSwicGF0aCI6Ii8xODI0ODkzOC8zMjc1NjU5NzAtYmUwZTZiNmItZGYyNy00M2JlLThkNzktOWQ4MTYzNzQ4MmUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDE5MzgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0MTc1MmQ3YmRiNWY0YzE3ZGRkMWNkMzQ4YTExYTQ4MDk4YTc0NTBiNDA3Yjc3NDMyZGI5MmRkZTk2NDZmMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aF7oZEmqAk5hV-KfEYPZlv247bUzH-qO2aPxVVyTBYI)

You should use `-fulluninstall` but this will delete everything

**Comment by kpetrow** [comment]
thats it thanks.
