### ISSUE TITLE
How to know latest available version for agents

### ISSUE THREAD

**Issue by tootai** [Ylianst/MeshAgent#250]
Hi,

looking on a Windows agent I saw that the version is from 9/12/2022. I started  manual update from console, after this version was still the same which means it's effectively the last version.

Is there a way to know from server or from repos which is the last available version pushed to client -for each OS-, same for Agent core ?

Daniel

**Comment by si458** [comment]
the is already a feature request in the meshcentral repo for this exact feature.
i will edit this post when i find the issue (unless u find it before me haha)

but sadly at the moment, the is no way of knowing if the is a new meshagent update waiting

the hasnt been an update to the raw EXE since 2022 but we do know we need to build new ones, and they are in the works

however when we update the meshcore.js in the meshcentral repo, this gets pushed automatcially directly to your remote devices, so new features/web ui improvements can get added with every release

**Comment by tootai** [comment]
Hi Simon. I know that updates are automagically pushed but you never know ;) and as security comes always in my mind, 18 monthes or so w/o new version is an alarm in my head (linux one is 21/11/2022), that's why I asked.

Sorry for the duplicate, I didn't read all opened issues :(. BTW, is there a way to get informed each time a new version/something important is published (telegram, wiki, forum, email, ...) ?

**Comment by si458** [comment]
@Ylianst was let go in 2022 from Intel, so funding for meshcentral stopped,
i decided to carry on fixing bug/adding features and help out with consulting on meshcentral.

you can check the github releases for new meshcentral versions - https://github.com/Ylianst/MeshCentral/releases

we also have a few chat rooms/help rooms
https://github.com/Ylianst/MeshCentral?tab=readme-ov-file#unofficial-chatrooms

and i personally use https://newreleases.io/ for notifications of github releases/docker releases/etc! (free too hehe)

if we did a new meshagent release (which i really want to do this year), you will see a commit in the release in meshcentral

and hopefully ill add a page into meshcentral web ui too tell u the versions of meshagent and when a new agent is available!

also dont forget to donate to help me keep up the work and carry on fixing/adding stuff for meshcentral ❤️ 
https://www.si458.co.uk/2024/01/05/donation/

**Comment by tootai** [comment]
Thanks, I joined Telegram and newreleases.io
