### ISSUE TITLE
MeshAgent server url local

### ISSUE THREAD

**Issue by lethach** [Ylianst/MeshAgent#252]
I used IIS for proxy:
Internet (hotro.lexuanthach.io.vn) <==>IIS<==>Proxy<==>localhost:8080 (TlsOffLoad)
MeshAgent server' URL is Local (see image below) so it cannot connect to my mesh server.
Please help me.
![loimeshagent](https://github.com/Ylianst/MeshAgent/assets/6271417/2ebc85f7-d5f5-404a-8578-659d6ae3f9fc)

**Comment by HuFlungDu** [comment]
Just a guess here, but if you are using TLS offload, you need to set the [certUrl](https://github.com/Ylianst/MeshCentral/blob/ee0018e4d108ee0ea0bed158fb1940e00c6f162f/meshcentral-config-schema.json#L1429) property in meshcentral. Point it at your reverse proxy and it will use the cert provisioned by that as its cert. Otherwise, it will force lanonly mode, because it doesn't recognize any certs and therefore does not know its domain name. You may also need to set the [cert](https://github.com/Ylianst/MeshCentral/blob/ee0018e4d108ee0ea0bed158fb1940e00c6f162f/meshcentral-config-schema.json#L14) property, but I'm not sure, since I haven't tried running without that property before.

**Comment by si458** [comment]
sorry only just seen this,
the only reason the meshagent shows `local` as the server url is because you havent set the `cert` value in your `config.json`
buf if you have then please share u `config.json` for us to work out why its showing `local`
