### ISSUE TITLE
Message Box in RDP Session

### ISSUE THREAD

**Issue by ryanblenis** [Ylianst/MeshAgent#27]
Hi @krayon007,

Thanks for the help pointing me in the right direction on #26 . Some testing with this brought up a different kind of bug. When the active user is in an RDP session, the message box does not show up, only when in a console session. Just wondering if there is a way to detect the active session and direct the message box appropriately. Thank you.

**Comment by krayon007** [comment]
Oh yes, I was working on that before the holidays. I added support for that for toasts and connection bar, but I think I forgot to add it for the message box. It's easy to add tho. I will add that as a parameter, where you can specify the TSID.

Currently, the message box looks for the console TSID, but i can make it so you can specify the TSID directly.

Enumerating the ID is already there in the user-sessions.js module. Ylian was modifying the UX so that it would detect if the logged on user is on a console or rdp session, and use the appropriate ID, only prompting the user if there is more than one active session.

**Comment by ryanblenis** [comment]
Awesome! Thank you! I can leave this open and close it when the feature is added or feel free to close if you don't prefer it for tracking. Thanks!

**Comment by krayon007** [comment]
Looks like support for this has been added a while ago.
