### ISSUE TITLE
[Question] on GenericMarshal

### ISSUE THREAD

**Issue by ryanblenis** [Ylianst/MeshAgent#28]
Hi @krayon007,

Wondering if you have any documentation / links on where/how you're getting the commands/interactions you use with GenericMarshal / CreateNativeProxy / CreateMethod to interact with Windows DLL's. Seems like this could be fairly powerful for some of my plugin work, but I'm trying to wrap my head around it's usage. I can see that you're interfacing directly with the Windows API's once you create it, but my Googling has not led me anywhere on the GenericMarshal / NodeJS front (even within Duktape.org). Any pointers / documentation would be greatly appreciated. Thank you!

**Comment by krayon007** [comment]
Hi,

YEah, you can't find anything on Google, because I wrote that API myself. I was originally planning to mirror FFI, but found that API to be rather bloated/complex for what I was using it for, plus I needed something with better thread control.

As far as documentation, I embedded the documentation in the code, so that you can use Doxygen to build the documentation... Altho I've since added many features to GenericMarshal since I last updated the embedded documentation, so I can update that, and integrate a small sample, or walk-thru or something similar.

The embedded documentation is at the end of the ILibDuktape_GenericMarshal.c file. Doxygen uses specially formatted comments...
You can probably refer to modules/win-registry.js to see how it's used, that's probably the simplest example. With win-message-pump.js being the most complex.

But to give a quick start right here:

Basically, you initialize it by calling CreateNativeProxy(), and passing in the name of the .dll you want to load. (It works with .so files on Linux, FreeBSD, etc, as well)

When you call CreateMethod(), you pass in the name of the method you want to load. If it can find that method is exported in the .dll, a method will be added with the same name to the object, otherwise it will throw an expection saying the method was not found.

You call the method, to call the native method. Two parameter types are supported. Number and _GenericMarshal.Variable. To pass a number, just pass a number literal. Otherwise, you need to call "CreateVariable()" to create a variable object. You pass in either the number of bytes to allocate, or a string value. If you pass a string value, it will allocate the correct number of bytes to copy the NULL terminated string. On Windows, you can pass a second options parameter object, where you can specify the boolan value 'wide'. If true, it will perform a MultiByteToWide UTF8 conversion to a wchar*.

For structs, you just pass in the number of bytes that the struct is, and then you can call toBuffer() on the object, and use the NodeJS buffer methods to populate the fields. Keep in mind how the struct is packed, as sometimes 64bit and 32bit structs in Win32 are packed differently. You can use the PointerSize property of GenericMarshal, which will return sizeof(void*), so you can correctly populate the struct.

For methods, where win32 will allocate memory for you, you can use CreatePointer(), which will essentially create a void**. The object has a Deref() method on it, where it will dereference the pointer.

The return value is a _GenericMarshal.Variable object encapsulating the return value. 

The Val property will just cast the pointer to an unsigned integer.
To read the variable as a string, there are three ways to do it... The 'String' property will just directly treat the variable as a char* and convert it to a JavaScript string. On Windows, there is also 'AnsiString' and 'WideToUTF8'. AnsiString, treats the variable as a wchar* and does a wide to multibyte conversion using ascii. WideToUTF8 does the same, but decodes the wchar as a UTF8 string. On non windows, these conversions are not necessary, because the underlying string is already UTF8.

If you need to copy pointer values around, like if you need to assign a reference to a struct inside another struct, you can use pointerBuffer(), which will return the pointer value of the object reference as a NodeJS buffer, so you can overwrite or read it's contents. Basically you use the copy() method to copy the values...

As far as threading goes, everything is always on the event loop thread. There are two ways to change this behavior. The first, is when calling "CreateMethod", pass in an options object as the second parameter, and specify the boolean property 'threadDispatch'. If true, this makes it so whenever you call the method, it will spawn a new thread, and use that thread to make the native call. The return value will be an event object instead of a Variable object, so you then just hookup to the 'done' event, where the only parameter in the dispatch will be the return result of the native call as a variable object. The thread will be cleaned up after the call completes. 

The other way to handle threading, is that every method (which is a function object), has an 'async()' function. Now this function can be called in two ways... If called normally, it will spawn a thread to do the native call on the spawned thread. The return value is a promise object that is resolved when the call completes. After which, the thread, is reused for the next async() call. You can also pass the async() function object in as the first parameter. For example, foo.TestMethod.async(foo.BarMethod.async). What this does, is allow you to dispatch the native call, using the thread of the passed in async method. If you refer to win-message-pump.js you'll see what I mean.. I use async to create a message pump thread, from which I need to use that exact thread to make other win32 calls, so that they are on the correct thread. 

If you call async.abort(), it will signal the worker thread to exit and cleanup.

Things get tricky, when you need to register for callbacks in win32, because the MeshAgent written in C as opposed to C++, so structs cannot have member functions... 
Basically you call 'GetGenericGlobalCallback()' and pass in the number of parameters the callback method has. The return value is a Variable object that can be passed to other native calls. This object has a 'GlobalCallback' event that can be hooked that will be dispatched when the callback is called by the system. Please note, that all global callbacks (hence the name) with the same number of parameters are shared. So when you hook the event, you need to inspect the parameters to make sure the event is actually for you. (The tricky part I referred to). if it's not for you, just do nothing. If it is for you, then you can do whatever you need to with it. Whatever value to return (must be a variable object), will get dispatched back to the originating calling thread, and returned in the native callback.

For special cases where a void*/user object is returned in the callback, I have a WrapObject() on GenericMarshal that will create a Variable object that you can pass that references the passed in Java Script object... Likewise, if you call UnWrapObject() and pass in a variable object, it will attempt to fetch the referenced javascript object, after doing some checks to make sure it is valid.

I know this is quite a lot to digest here, so feel free to comment back, and I'd be happy to answer any questions. You can email me to, but others may be interested in the conversation as well, so this thread is probably the best place to have that conversation...

**Comment by ryanblenis** [comment]
Amazing. Thank you for taking the time to write that up. I'm a few years out of practice on my C since the higher level languages made my life incrementally easier so it might take me a bit to work through, but the level of potential power and integration this provides is too good to pass up. I will no doubt be back with some follow up questions once I figure out how I want to take advantage of this functionality. I didn't have a plugin in mind when I asked the original question, but since it does .so's as well I may very well take a run at an ESET [ESMC](https://help.eset.com/esmc_install/70/api/) plugin to integrate endpoint protection into MeshCentral with ESET as a test project in the near future when I can find some spare time. Thank you for this and pointing me in the right direction!
