### ISSUE TITLE
Meshagent wont work with Cloudflare?

### ISSUE THREAD

**Issue by killmasta93** [Ylianst/MeshAgent#31]
Hi,
I was wondering if anyone else has happened to them as im trying to configure cloudflare proxy but as soon as i update on the Cloudflare DNS platform the agents die, wont connect as soon i remove the proxy on the platform of cloudflare it starts working again

Thank you

**Comment by jsastriawan** [comment]
Does that proxy support Websocket? MeshAgent connection uses Secure Websocket.

**Comment by killmasta93** [comment]
Thanks for the reply, im attaching photo on cloudflare it shows this 
![image](https://user-images.githubusercontent.com/13953629/72478097-2955ee00-37bf-11ea-9eec-6e09d12b9d23.png)

**Comment by killmasta93** [comment]
I was reading on the Help on cloud flare it says this 
```

Can I use WebSockets over SSL?

Yes, Cloudflare SSL fully supports WebSockets traffic passing through our network.
```

**Comment by killmasta93** [comment]
bump anyone else?

**Comment by masonh** [comment]
The Cloudflare proxy does TLS termination in their network, so the client will see a Cloudflare TLS certificate rather than the one configured on your MeshCentral server. As far as I know, there is no way to make Cloudflare proxy the traffic "dumbly".
You can verify whether this issue affects you by checking the MeshCentral logs, where connecting clients along with their observed/expected TLS certificate fingerprints are shown.
The solution would be to either use the same TLS certificate on your server as on Cloudflare, or set the MeshCentral TLS offload certUrl, which may also require turning off TLS in MeshCentral.
See the [User Guide](https://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2UserGuide.pdf) for more info on TLS Offloading.
Disclaimer: I haven't tried to do this myself, because of the complexity involved and my preference for keeping the TLS session private between clients and MeshCentral.

**Comment by killmasta93** [comment]
Thanks for the reply, forgot to close this as meshserver had an update for cloudflare proxy 
https://meshcentral2.blogspot.com/2020/12/meshcentral-ioactive-security-review.html
