### ISSUE TITLE
History being spammed with dbus-monitor commands

### ISSUE THREAD

**Issue by JustTNE** [Ylianst/MeshAgent#38]
https://github.com/Ylianst/MeshAgent/blob/fbd67d2c9c3091d1781c3e3ab3e46fdf051b12f9/modules/linux-dbus.js#L28 spams the bash history with dbus-monitor commands. You should probably use sh -c "cmd" to run the command instead of using stdin to write to the shell, or just not use a shell at all.

**Comment by krayon007** [comment]
I'll take a look at this after the holiday weekend

**Comment by TotallyNotElite** [comment]
Any updates on this yet?

**Comment by krayon007** [comment]
Not yet, but I think the solution might be really easy. Currently, dbus-monitor is spawned in interactive mode, which is actually unnecessary. I'm thinking if I instead spawn it in non-interactive mode it won't spam bash history. I'll test it on Monday.

**Comment by TotallyNotElite** [comment]
> Not yet, but I think the solution might be really easy. Currently, dbus-monitor is spawned in interactive mode, which is actually unnecessary. I'm thinking if I instead spawn it in non-interactive mode it won't spam bash history. I'll test it on Monday.

That would work, but there's no reason to use stdin to write the command in the first place.

**Comment by krayon007** [comment]
Unless I'm doing something wrong, I found that I couldn't spawn dbus-monitor directly, because the output isn't written to stdout, so I couldn't parse the output. I had to pipe the command and do a read, and manually echo it, to force it to stdout... Doing that, I had to use stdin and spawn SH in noninteractive mode, otherwise the pipe wouldn't work.

**Comment by krayon007** [comment]
Please re-open this if you are still experiencing this issue
