### ISSUE TITLE
Agent Crashes (Win10 1903 & 1909)

### ISSUE THREAD

**Issue by ryanblenis** [Ylianst/MeshAgent#46]
Hi @krayon007 ,

I'm seeing issues with several clients where the MeshAgent crashes frequently. I see the same log entry in each.

Server version: 0.5.31
Agent version: {
  "openssl": "1.1.1g",
  "duktape": "v2.3.0",
  "meshAgent": "2020-05-08T08:18:21.000Z"
}
Seems like everyone is 64 bit, so I can't test with a 32 bit agent OS to see if it makes any difference.

Errors:
```
Agent 1 example:
[2020-05-15 09:26:08 AM] FATAL EXCEPTION [MeshAgent_72C50F4A2BFDE64F.exe] @ [FuncAddr: 0x00007ff6b6e431bb / BaseAddr: 0x00007ff6b6e3e878 / Delta: -18755]
Agent 2 example:
[2020-05-15 02:15:50 PM] FATAL EXCEPTION [MeshAgent_72C50F4A2BFDE64F.exe] @ [FuncAddr: 0x00007ff7a0f231bb / BaseAddr: 0x00007ff7a0f1e878 / Delta: -18755]
Agent 3 example:
[2020-05-15 10:37:54 AM] FATAL EXCEPTION [MeshAgent_72C50F4A2BFDE64F.exe] @ [FuncAddr: 0x00007ff73b0c31bb / BaseAddr: 0x00007ff73b0be878 / Delta: -18755]
```

I'm seeing it every ~7-20 minutes on clients, where they crash and need to wait for the agent to restart. I don't know how to equate the FuncAddr and BaseAddr to the offending code. Hoping you can help here.

Full disclosure, I'm using these agents purely to let people "Work From Home" by routing their RDP through a tunnel via the MeshAgent with my [Work From Home](https://github.com/ryanblenis/MeshCentral-WorkFromHome) plugin (just in case that address space points to something odd that you can't follow in the agent specifically). 

Let me know anything I can do to help narrow down the cause. Thank you!

Note that the WorkFromHome plugin really just [mimics](https://github.com/ryanblenis/MeshCentral-WorkFromHome/blob/master/modules_meshcore/workfromhome.js#L212) what the MeshCmd [uses](https://github.com/Ylianst/MeshCentral/blob/master/agents/meshcmd.js#L2189) to set up a port / tunnel

**Comment by krayon007** [comment]
Are you able to enable core dumps? A dump is much more useful than the funcaddr thing...
I overhauled the windows agent tho (I haven't merged yet), to improve stability. I basically was able to do away with the this thing I called the Windows Run Loop, I had on Windows, as a majority of the crashes were related to thread synchronization issues... I had two processing loops on windows becuase windows has two different kinds of descriptors that use different asynchronous mechanisms, but I found a way to unify the two descriptor types so that I can use a single processing/event loop....

**Comment by ryanblenis** [comment]
I'll wait for the new agent to see if the issue resolves. It does seem like it would be a threading issue, as I can make the tunnel disconnect occur by connecting/disconnecting via Remote Desktop to an agent (though it doesn't crash, just disconnects the tunnel momentarily)- so hopefully the updates you're already working on fixes it, if not I'll post some more info with core dumps enabled. I'll be keeping an eye out for the new agent release. Thank you!  

PS if you think the timeline is long or prefer coredumps in the current state versus waiting just let me know and I can turn them on and get some info.

**Comment by ryanblenis** [comment]
Hi @krayon007,

Updated the server to 0.5.38 and still see the issue with crashing. I've emailed you a core dump right after the issue occurred. Thank you!

**Comment by krayon007** [comment]
Thanks for the dump. I added a check for the specific case that caused your crash. It was inside one of the finalizer routines. I'm currently updating some HECI/AMT related stuff, so it'll be part of the next agent update. After I finish that, I'll look at updating the EventEmitter (which is where the crash happened) to be robust. I wrote that particular object at the very beginning (since everything needs an event emitter), and there are some tricks that I use now that I didn't know back then. For example, when I first wrote it, I was using a native data structure to hold all the references inside the event emitter, to subscribers... However, native references to JS objects are weak, in that they are invisible to the GC. So I circumvented that by using an embedded 'hidden' object where I stashed the references. Works fine for most things, except for the event emitter itself, becuase when it emits an event, it could be possible that it triggers a series of events that causes the event emitter itself to get GC'ed, which is where your crash happened.

A while ago, I created some APIs so that I could use a JS data structure instead of a native one, so that I could add JS objects to it directly, in which case, the references are strong instead of weak, so I don't need to bother with embedded 'hidden' objects. This way, if the finalizer collects the object, it's fine, because there is nothing to clean up, unlike the hidden object, because I need to clean up the native data structure in that case.

**Comment by ryanblenis** [comment]
Awesome, thank you! I'd love to get more involved with the agent code, but there's so much to learn (that I've forgotten over the years since using higher level languages). There's so much to learn to get familiar with the project code!
