### ISSUE TITLE
Document how to build meshcmd

### ISSUE THREAD

**Issue by nomis** [Ylianst/MeshAgent#60]
I want to modify `meshcmd` to support loading installed a certificate signed by CA external to MeshCommander, but I can't tell how to build it.

I can compile the contents of MeshAgent and then try to run `meshcmd.js` but it fails trying to use anything located in the `microscript` directory:
```
Error: Cannot find module 'MD5Stream'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/simon/src/MeshAgent/modules/http-digest.js:19:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by krayon007** [comment]
You should use the meshcmd.js that is in the MeshCentral repo. I don't think Ylian updated the one that is in the agent repo...
The easiest way to test your modifications, is to do this (assuming you built the latest meshagent). Make sure you build either for Debug or Release, not the No_OpenSSL or Library configurations. 

1. Zip the MeshCentral/agents/modules_meshcmd folder. (zip the folder, not the contents)
2. Add meshcmd.js to the root of the zip file
 
You can then run meshcmd, by running the agent, specifying the zip file in the command line... Like:

MeshService64.exe meshcmd.zip

If the above doesn't work, you need to pull the agent repo, and rebuild, as I recently fixed a bug where only the console app was capable of running zip files instead of both the console and service app.

@Ylianst can chime in with instructions for how he actually builds meshcmd.

**Comment by krayon007** [comment]
Note: The easiest way to build the zip file, is to navigate to the MeshCentral/agents folder. Single click meshcmd.js, then while it's still selected, ctrl-click the modules_meshcmd folder, then right click, and Send To Compressed Folder...

**Comment by nomis** [comment]
Your instructions assume I'm using Windows but I'm using Linux.

There's no reason why I should need to run meshcmd using any other executable component when it is available as a separate executable. The version in this repo is out of date but the other repo does not have all of the dependencies.

It's ok, I'm now using [sdague/amt](https://github.com/sdague/amt) instead.

**Comment by krayon007** [comment]
The same zip file will work on all platforms. The dependencies are actually not missing, they are in the modules folder. The only reason I told you to zip the modules_meshcmd folder, is so that you don't zip modules that aren't needed. But it will also work if you just zip the entire modules folder in the agent repo. The only file that was out of date is meshcmd.js

The reason you were getting those errors, is because you didn't link any of the dependencies. The actual meshcmd executable is actually the exact same agent executable, with all the dependencies encapsulated.

The only reason I suggested using this zip method, was so it you can test your changes without having to rebuild each time... You can in-line edit the meshcmd.js file and relaunch to immediately test your changes.
