### ISSUE TITLE
Question: Is there a keep-alive mechanism on meshagent?

### ISSUE THREAD

**Issue by steuck13** [Ylianst/MeshAgent#64]
Greetings
I'd like to know if meshagent has a keep-alive to keep it's connection state consistent with the server. I saw the server has an 'AgentPing' option but that demands an action from the server, the agent only respond.

**Comment by krayon007** [comment]
Yes. The agent uses a websocket ping control message. By default it sends one after every 2 minutes of inactivity, but it can be configured by setting controlChannelIdleTimeout in the msh to the number of seconds.

**Comment by Ylianst** [comment]
The websocket ping control message may not be seen as "real" data by some reverse proxies. So, you can use the following values in the settings section of config.json if you need "real" data to be generated.

    "BrowserPing": 60,
    "BrowserPong": 60,
    "AgentPing": 60,
    "AgentPong": 60

Note that "Ping" will send to the agent/browser and ask for a response. "Pong" will send to the agent/browser but not ask for a response. It's generally best to have this be server set since you can easily change it as needed. Let me know if you are asking for more than this.

**Comment by steuck13** [comment]
Tyvm all for your responses. I'll close it now.
