### ISSUE TITLE
MeshAgent Win service not installing

### ISSUE THREAD

**Issue by BradleyShaner** [Ylianst/MeshAgent#66]
I've been trying to get the MeshAgent to install at bootup with a GPO batch file. The initial copying and executing isn't an issue.

The problem comes when running the -install or -fullinstall switches.

It does this (below) and then stops. Indefinitely. It also doesn't run the remainder of the batch file. The install seems to be stuck in a loop.
```
...Checking for previous installation [NONE]
...Installing service
```
This happens on machines with and without an AV installed, including Windows Defender disabled.

Is there a way to troubleshoot/debug this? There's no additional error or output.

**Comment by krayon007** [comment]
What server version are you using? Which windows OS are you running? Is this 32 or 64 bit agent?

**Comment by LostSoulfly** [comment]
> What server version are you using? Which windows OS are you running? Is this 32 or 64 bit agent?

Oops, sorry. Should have included that.

x64 agent on Windows 10 Pro release 2004.

I've been experimenting with creating the service using `sc create` and I think it's working but needs more testing to be certain.

```
> versions
{
    "node": "12.18.3",
    "v8": "7.8.279.23-node.39",
    "uv": "1.38.0",
    "zlib": "1.2.11",
    "brotli": "1.0.7",
    "ares": "1.16.0",
    "modules": "72",
    "nghttp2": "1.41.0",
    "napi": "6",
    "llhttp": "2.0.4",
    "http_parser": "2.9.3",
    "openssl": "1.1.1g",
    "cldr": "37.0",
    "icu": "67.1",
    "tz": "2019c",
    "unicode": "13.0"
}
```

**Comment by krayon007** [comment]
So I assume the install script is running as NT AUTHORITY\\SYSTEM, as opposed to a logged in user?

**Comment by LostSoulfly** [comment]
> So I assume the install script is running as NT AUTHORITY\SYSTEM, as opposed to a logged in user?

Yes, that's indeed how the login script GPO works. However with psexec it runs as my user (domain\username) on the remote system with elevated rights.

I'm not sure how important the SID is but I'm able to install the service manually with this:
`sc create "Mesh Agent" binPath= "C:\\Work\\Mesh\\MeshAgent.exe --installedByUser=\"S-1-5-21-963930013-4238468522-2026462934-1311\"" type= own type= interact error= ignore start= auto`

So long as I name the service "Mesh Agent" the uninstall seems to process as expected.

That is my SID. It can't be looked up locally on the computer because it's a domain account so it must contact a DC as it's never been used to log into the remote machine.

**Comment by krayon007** [comment]
Ok, it looks like you are running Server version 0.6.29.. I previously fixed a bug in the installer that happens when the user that runs the installer is not a logged in user... But that fix is included in server version 0.6.33 and newer... If you update your server to a newer version, you should be able to correctly install the agent with your GPO script.

**Comment by LostSoulfly** [comment]
I've upgraded my server to 0.6.40.

```
{
    "rss": 108494848,
    "heapTotal": 36540416,
    "heapUsed": 35184984,
    "external": 46931962,
    "arrayBuffers": 45445439,
    "dbType": "MongoDB",
    "dbChangeStream": false,
    "plugins": [
        "workfromhome"
    ],
    "nodeVersion": "v12.18.3",
    "meshVersion": "0.6.40",
    "platform": "linux",
    "arch": "x64",
    "pid": 21,
    "uptime": 1624.754717061,
    "cpuUsage": {
        "user": 3708342,
        "system": 296009
    },
    "warnings": [],
    "database": "MongoDB",
    "productionMode": true,
    "allDevGroupManagers": []
}
```


The agent appears to be the same filesize and version:
![image](https://user-images.githubusercontent.com/9120519/93519593-63eaca00-f8fc-11ea-8140-eede6ea607a8.png)![image](https://user-images.githubusercontent.com/9120519/93520677-d9569a80-f8fc-11ea-90bf-f4237fe0cd1f.png)


With the same problem:
![image](https://user-images.githubusercontent.com/9120519/93520610-be842600-f8fc-11ea-8216-f844a716f893.png)

**Comment by krayon007** [comment]
If you run: MeshAgent -info
What does it dispay?

**Comment by krayon007** [comment]
This is the original bug I was referring. Looks like your symptoms are slightly different:
https://github.com/Ylianst/MeshCentral/issues/1792

So if I'm understanding what you said, you're saying your GPO installer script is running the agent installer as a domain user that has never logged into the machine before? If so, I may have to give you an instrumented version of the installer (or at least update the installer to include a verbose mode), to try to figure out where it's getting stuck.

**Comment by LostSoulfly** [comment]
Here's the -info
![image](https://user-images.githubusercontent.com/9120519/93537794-812e9100-f91a-11ea-9857-08ebdde70c27.png)

**Comment by krayon007** [comment]
If you still are experiencing this issue, please re-open this issue
