### ISSUE TITLE
Wrong agent version displayed in windows prebuilt agent

### ISSUE THREAD

**Issue by jbfuzier** [Ylianst/MeshAgent#67]
Hello,

It seems the agent version number of the windows exe is not updated; which makes it hard to know which version is installed on the PC.

![image](https://user-images.githubusercontent.com/4688432/97680985-d8865c00-1a97-11eb-8c63-cd016e450848.png)

Also, is there a way to know in meshcentral which version is running on a host ?

Thanks for your help

**Comment by krayon007** [comment]
Are you asking about querying the agent version from the server side or the client side? From the client side, you can query the version from the command line, like this:
`MeshAgent -info`

This will fetch the compile date/time, the commit hash, and the commit date/time.
The version semantics built into windows didn't offer enough granularity, which is why it wasn't updated. The metadata in the `-info` switch above, is populated at compile time automatically in the build script.

**Comment by krayon007** [comment]
Also, the version semantics of the `-info` is consistent across all supported platforms, Windows, Linux, macOS, FreeBSD, etc.

**Comment by jbfuzier** [comment]
My bad, I made a mistake. I thought the User's Guide v0.2.9 meant user guide for agent v0.2.9 while it is in fact the version of the user guide. So the most recent version of the agent at that time was indeed 0.2.1.3.

It would be nice to be able to see the agent version in the webui though... (Or maybe I missed it)
