### ISSUE TITLE
unable to open database

### ISSUE THREAD

**Issue by luckydonald** [Ylianst/MeshAgent#9]
On windows 10 pro, MC 0.3.0-n
```cmd
C:\Windows\System32>"C:\Program Files (x86)\Mesh Agent\MeshAgent.exe" run
MeshCentral2 Agent
Unable to open database (1/10)...
Unable to open database (2/10)...
Unable to open database (3/10)...
Unable to open database (4/10)...
Unable to open database (5/10)...
Unable to open database (6/10)...
Unable to open database (7/10)...
Unable to open database (8/10)...
Unable to open database (9/10)...
Unable to open database (10/10)...
Unable to open database.
```

![image](https://user-images.githubusercontent.com/2737108/54476178-79a89c00-47fa-11e9-8d54-c84b9e25d24a.png)

**Comment by krayon007** [comment]
You can't run two instances of the agent from the same location simultaneously, that's why it says can't open database. If you want to run the agent in console mode with the "run" parameter, you need to stop the service first.

**Comment by luckydonald** [comment]
Can't test right now, but do I need to execute `cmd.exe` and thus `MeshAgent.exe` as Administrator here for the database to be expected to work? 
Not using `sudo` was the problem on the [mac side](https://github.com/Ylianst/MeshAgent/issues/10#issuecomment-473605557)

**Comment by krayon007** [comment]
It depends on how the db was created. If the service created the db, then yes, because filesystem will show the owner of the file being SYSTEM. However, if you run the agent as a user in console mode first, so that the db was created with the owner set to an individual user, then no.

Since in your snippet, it shows it's running in program files, most likely the service created the db... (On windows, if you use the command line to install the service, it installs the service, it configures the service to run the binary where it is, rather then moving it to program files. In this scenario, typically the user owns the db file.
