### ISSUE TITLE
File Size Limit

### ISSUE THREAD

**Issue by geoff-scott** [Ylianst/MeshAgent#93]
Hello,

First I would like to say that I am exceptionally happy with the quality of this product. The team has done amazing things. You guys rock!

There seems to be a problem with the file sizes when transferring files via the FILES module. Currently, there is no way to exceed 2GB when transferring. The system just hangs there, but for anything less than 2GB, the transfer works perfectly. I did discover this when I was attempting to transfer a WindowsISO to my server (3.2GB).

Is there a setting that needs to be changed in the configuration file? Or is this a legitimate bug I don't know for sure?

Any help here would be greatly appreciated.

Thank you,

Geoff

The version of the software you are using
Windows 10 Chrome Browser Client transferring to, Linux 20.04 LTS Host

![image](https://user-images.githubusercontent.com/71340280/120366356-8fbcad00-c2dd-11eb-98de-6698977d9a7e.png)

**Comment by krayon007** [comment]
Are you uploading a file to the agent, or downloading a file from the agent?

**Comment by geoff-scott** [comment]
Uploading the file from my machine to the agent.On Jul. 6, 2021 7:34 p.m., Bryan Roe ***@***.***> wrote:
Are you uploading a file to the agent, or downloading a file from the agent?

**Comment by geoff-scott** [comment]
@krayon007 I am just following up with our comments to each other. I responded about a month ago. 

"Uploading the file from my machine to the agent"

Has this bug been fixed or is this a limitation of the software?

**Comment by krayon007** [comment]
Hi, sorry I haven't had a chance to fix this yet, as it is not simple to fix. The underlying issue, is that JavaScript does not normally support unsigned values, nor has primitive support for 64 bit integer values. 

For the most part I've been following node APIs. The stream object uses signed 32 bit values. Normally this shouldn't be an issue when appending to a file, but I'm not sure about the browser API for reading a file. I also have to double check my writes to disc because I remember the async API that I was using required that I specify the position value. I'm pretty sure I used a uint32 for this, but I have to double check.

As long as it's not a browser issue, I may be  able to work around this, but it may be involved and require lots of testing.

Thanks for your patience.

**Comment by geoff-scott** [comment]
@krayon007 - Thank you for your response, it has been some time since your last message. I was hoping there was some progress on this particular issue.

Please advise

Thank you,
Geoff

**Comment by krayon007** [comment]
I apparently misread the specification that described 'integer', and didn't need to artificially constrain myself to using a signed 32 bit integer... I should be able to fix this, by switching the primative that I'm using. I'll have to switch this in a bunch of places tho..

**Comment by krayon007** [comment]
I wrote several test cases, and it looks like this was actually a browser side issue. Ylian wrote a server side fix for this. I'll ask him what version of the server contains this fix.

**Comment by geoff-scott** [comment]
@krayon007 Happy New Year! I hope you had a wonderful holiday.

Thank you for doing this...this will help a lot with my use case scenario.

Has @Ylianst responded to your request? 

Also if he has responded, what version of the server do I need to implement the fix?

Thank you,
Geoff

**Comment by krayon007** [comment]
He updated a few times, since the new years, so it should be live now.
